name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7.3
      - run: julia -e 'using Pkg; Pkg.add("BinaryBuilder")'
      - run: BINARYBUILDER_AUTOMATIC_APPLE=true julia build_tarballs.jl
      - name: release
        uses: ncipollo/release-action@v1.10.0
        id: create_release
        with:
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          artifactContentType: application/gzip
          artifacts: products/?linux-gnu.*,products/?x86_64-apple-darwin.*,products/?aarch64-apple-darwin.*
        env:
          GITHUB_TOKEN: ${{ github.token }}