name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7.3
      - run: julia -e 'using Pkg; Pkg.add("BinaryBuilder")'
      - run: BINARYBUILDER_AUTOMATIC_APPLE=true julia build_tarballs.jl
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            products/?linux-gnu.*
            products/?x86_64-apple-darwin.*
            products/?aarch64-apple-darwin.*
