name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: checkout
        uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7.3
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/build_tarballs.jl') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: julia -e 'using Pkg; Pkg.add("BinaryBuilder")'
      - run: BINARYBUILDER_AUTOMATIC_APPLE=true julia build_tarballs.jl
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            products/tpch_dbgen.${{ steps.vars.outputs.tag }}.x86_64-linux-gnu.tar.gz
            products/tpch_dbgen.${{ steps.vars.outputs.tag }}.x86_64-apple-darwin.tar.gz
            products/tpch_dbgen.${{ steps.vars.outputs.tag }}.aarch64-apple-darwin.tar.gz
